CREATE TABLE IF NOT EXISTS users(
    id BIGINT AUTO_INCREMENT,
   first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL UNIQUE,
   password  VARCHAR(255) NOT NULL,
   is_connected TINYINT(1) DEFAULT 0,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS posts (
    id BIGINT AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    post_id BIGINT  NULL,
    content TEXT,
    image_path VARCHAR(255) NULL,
    created_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    updated_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, -- suppresion automatique si l'user part--
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS comments(
    id BIGINT AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    updated_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE, -- Suppression auto si le post est effacé
    PRIMARY KEY(id)

);

CREATE TABLE IF NOT EXISTS likes (
    id BIGINT AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,
    UNIQUE KEY user_post_unique (user_id, post_id) -- Empêche le double like
);


CREATE TABLE IF NOT EXISTS messages (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    sender_id BIGINT UNSIGNED NOT NULL,
    receiver_id BIGINT UNSIGNED NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT fk_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_receiver FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;